[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
markers = [
    "slow: marks tests as slow",
    "training: marks tests as involving a training step",
    "scaling: marks tests as involving a scaling study",
    "constraint: marks tests as explicitly testing constraint capabilities",
    "factor: marks test as explicitly testing factor capabilities",
    "timing: marks test as explicitly involving wallclock time calculations"
]